# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AccountRegist.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        MainWindow.setMinimumSize(QtCore.QSize(800, 480))
        MainWindow.setMaximumSize(QtCore.QSize(800, 480))
        MainWindow.setStyleSheet("#MainWindow{border-image: url(:/lay/account.PNG);}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.NewAccountBox = QtWidgets.QLineEdit(self.centralwidget)
        self.NewAccountBox.setGeometry(QtCore.QRect(270, 135, 320, 30))
        self.NewAccountBox.setMinimumSize(QtCore.QSize(320, 30))
        self.NewAccountBox.setMaximumSize(QtCore.QSize(600, 40))
        self.NewAccountBox.setObjectName("NewAccountBox")
        self.RegistcaseShow = QtWidgets.QLineEdit(self.centralwidget)
        self.RegistcaseShow.setGeometry(QtCore.QRect(270, 260, 321, 30))
        self.RegistcaseShow.setMinimumSize(QtCore.QSize(300, 30))
        self.RegistcaseShow.setMaximumSize(QtCore.QSize(400, 30))
        self.RegistcaseShow.setStyleSheet("border: none")
        self.RegistcaseShow.setAlignment(QtCore.Qt.AlignCenter)
        self.RegistcaseShow.setReadOnly(True)
        self.RegistcaseShow.setObjectName("RegistcaseShow")
        self.NewKeyBox = QtWidgets.QLineEdit(self.centralwidget)
        self.NewKeyBox.setGeometry(QtCore.QRect(270, 175, 320, 30))
        self.NewKeyBox.setMinimumSize(QtCore.QSize(320, 30))
        self.NewKeyBox.setMaximumSize(QtCore.QSize(600, 40))
        self.NewKeyBox.setEchoMode(QtWidgets.QLineEdit.Password)
        self.NewKeyBox.setObjectName("NewKeyBox")
        self.SureBox = QtWidgets.QLineEdit(self.centralwidget)
        self.SureBox.setGeometry(QtCore.QRect(270, 215, 320, 30))
        self.SureBox.setMinimumSize(QtCore.QSize(320, 30))
        self.SureBox.setMaximumSize(QtCore.QSize(600, 40))
        self.SureBox.setEchoMode(QtWidgets.QLineEdit.Password)
        self.SureBox.setObjectName("SureBox")
        self.NewIdBt = QtWidgets.QPushButton(self.centralwidget)
        self.NewIdBt.setGeometry(QtCore.QRect(270, 305, 100, 40))
        self.NewIdBt.setMinimumSize(QtCore.QSize(100, 40))
        self.NewIdBt.setMaximumSize(QtCore.QSize(100, 40))
        self.NewIdBt.setStyleSheet("border-radius:10px;padding:2px 4px;\n"
"font: 75 10pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 0);")
        self.NewIdBt.setObjectName("NewIdBt")
        self.AccountBackBt = QtWidgets.QPushButton(self.centralwidget)
        self.AccountBackBt.setGeometry(QtCore.QRect(490, 305, 100, 40))
        self.AccountBackBt.setMinimumSize(QtCore.QSize(100, 40))
        self.AccountBackBt.setMaximumSize(QtCore.QSize(100, 40))
        self.AccountBackBt.setStyleSheet("border-radius:10px;padding:2px 4px;\n"
"font: 75 10pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 0);")
        self.AccountBackBt.setObjectName("AccountBackBt")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.NewIdBt.setText(_translate("MainWindow", "创建"))
        self.AccountBackBt.setText(_translate("MainWindow", "返回"))
import welcome_rc
