# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        MainWindow.setMinimumSize(QtCore.QSize(800, 480))
        MainWindow.setMaximumSize(QtCore.QSize(800, 480))
        MainWindow.setStyleSheet("#MainWindow{background-color: rgb(255, 255, 255);}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(800, 50))
        self.frame.setMaximumSize(QtCore.QSize(800, 50))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMinimumSize(QtCore.QSize(38, 36))
        self.frame_3.setMaximumSize(QtCore.QSize(38, 36))
        self.frame_3.setStyleSheet("border-image: url(:/lay/trainmark.jpg);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout.addWidget(self.frame_3, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMinimumSize(QtCore.QSize(200, 40))
        self.label.setMaximumSize(QtCore.QSize(200, 40))
        self.label.setStyleSheet("font: 6pt \"华文行楷\";\n"
"background-color: rgb(255, 255, 255);")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.time_fm = QtWidgets.QLabel(self.frame)
        self.time_fm.setMinimumSize(QtCore.QSize(500, 40))
        self.time_fm.setMaximumSize(QtCore.QSize(500, 40))
        self.time_fm.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 13pt \"方正姚体\";\n"
"")
        self.time_fm.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.time_fm.setObjectName("time_fm")
        self.gridLayout.addWidget(self.time_fm, 0, 2, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 0, 0, 1, 3)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(90, 270))
        self.frame_2.setMaximumSize(QtCore.QSize(90, 270))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3.addWidget(self.frame_2, 1, 0, 1, 1)
        self.DispLb = QtWidgets.QLabel(self.centralwidget)
        self.DispLb.setMinimumSize(QtCore.QSize(580, 270))
        self.DispLb.setMaximumSize(QtCore.QSize(580, 270))
        self.DispLb.setFrameShape(QtWidgets.QFrame.Box)
        self.DispLb.setText("")
        self.DispLb.setObjectName("DispLb")
        self.gridLayout_3.addWidget(self.DispLb, 1, 1, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setMinimumSize(QtCore.QSize(90, 270))
        self.frame_4.setMaximumSize(QtCore.QSize(90, 270))
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_3.addWidget(self.frame_4, 1, 2, 1, 1)
        self.buttonfm = QtWidgets.QFrame(self.centralwidget)
        self.buttonfm.setMinimumSize(QtCore.QSize(780, 30))
        self.buttonfm.setMaximumSize(QtCore.QSize(780, 50))
        self.buttonfm.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.buttonfm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttonfm.setObjectName("buttonfm")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.buttonfm)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ShowBt = QtWidgets.QPushButton(self.buttonfm)
        self.ShowBt.setMinimumSize(QtCore.QSize(100, 35))
        self.ShowBt.setMaximumSize(QtCore.QSize(100, 35))
        self.ShowBt.setStyleSheet("background-color: rgb(193, 193, 193);")
        self.ShowBt.setObjectName("ShowBt")
        self.gridLayout_2.addWidget(self.ShowBt, 0, 0, 1, 1)
        self.Outscreen = QtWidgets.QPushButton(self.buttonfm)
        self.Outscreen.setMinimumSize(QtCore.QSize(100, 35))
        self.Outscreen.setMaximumSize(QtCore.QSize(100, 35))
        self.Outscreen.setStyleSheet("background-color: rgb(193, 193, 193);")
        self.Outscreen.setObjectName("Outscreen")
        self.gridLayout_2.addWidget(self.Outscreen, 0, 3, 1, 1)
        self.gostop = QtWidgets.QLabel(self.buttonfm)
        self.gostop.setMinimumSize(QtCore.QSize(500, 60))
        self.gostop.setMaximumSize(QtCore.QSize(500, 60))
        font = QtGui.QFont()
        font.setFamily("方正姚体")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.gostop.setFont(font)
        self.gostop.setStyleSheet("font: 15pt \"方正姚体\";\n"
"background-color: rgb(255, 255, 255);")
        self.gostop.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.gostop.setObjectName("gostop")
        self.gridLayout_2.addWidget(self.gostop, 0, 2, 1, 1)
        self.gridLayout_3.addWidget(self.buttonfm, 2, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "神荼系统"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">联合车站</span></p></body></html>"))
        self.time_fm.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.ShowBt.setText(_translate("MainWindow", "开始识别"))
        self.Outscreen.setText(_translate("MainWindow", "退出"))
        self.gostop.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))

import trainmark_rc
