# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Systemoff.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Sysoffwindow(object):
    def setupUi(self, Sysoffwindow):
        Sysoffwindow.setObjectName("Sysoffwindow")
        Sysoffwindow.resize(800, 480)
        Sysoffwindow.setMinimumSize(QtCore.QSize(800, 480))
        Sysoffwindow.setMaximumSize(QtCore.QSize(800, 480))
        Sysoffwindow.setStyleSheet("#Sysoffwindow{border-image: url(:/lay/traininrail.jpg);}")
        self.centralwidget = QtWidgets.QWidget(Sysoffwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.OpenBt = QtWidgets.QPushButton(self.centralwidget)
        self.OpenBt.setGeometry(QtCore.QRect(300, 370, 200, 40))
        self.OpenBt.setMinimumSize(QtCore.QSize(200, 40))
        self.OpenBt.setMaximumSize(QtCore.QSize(200, 40))
        self.OpenBt.setStyleSheet("font: 18pt \"楷体\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.OpenBt.setObjectName("OpenBt")
        Sysoffwindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Sysoffwindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        Sysoffwindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Sysoffwindow)
        self.statusbar.setObjectName("statusbar")
        Sysoffwindow.setStatusBar(self.statusbar)

        self.retranslateUi(Sysoffwindow)
        QtCore.QMetaObject.connectSlotsByName(Sysoffwindow)

    def retranslateUi(self, Sysoffwindow):
        _translate = QtCore.QCoreApplication.translate
        Sysoffwindow.setWindowTitle(_translate("Sysoffwindow", "神荼系统"))
        self.OpenBt.setText(_translate("Sysoffwindow", "开启系统"))
import traininrail_rc
import welcome_rc
